"""Change portait_url to portrait_url

Revision ID: 0dfc9b1ee25c
Revises: 454783c2f1b7
Create Date: 2021-04-24 07:49:48.319310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dfc9b1ee25c'
down_revision = '454783c2f1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'portait_url', nullable=True, new_column_name='portrait_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'portrait_url', nullable=True, new_column_name='portait_url')
    # ### end Alembic commands ###
