"""Add movie_photo and portait_url

Revision ID: 454783c2f1b7
Revises: 9428b6a6871c
Create Date: 2021-04-12 20:57:00.743061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454783c2f1b7'
down_revision = '9428b6a6871c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('portait_url', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('movie_photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'movie_photo')
    op.drop_column('actors', 'portait_url')
    # ### end Alembic commands ###
